"""add components and service records

Revision ID: 16037b9b34c8
Revises: 724fc5983761
Create Date: 2026-04-09 10:51:34.804186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16037b9b34c8'
down_revision: Union[str, Sequence[str], None] = '724fc5983761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_category', sa.String(length=50), nullable=False),
    sa.Column('mileage_at_service', sa.Integer(), nullable=True),
    sa.Column('is_diy', sa.Boolean(), nullable=False),
    sa.Column('next_service_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_record_components',
    sa.Column('service_record_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_record_id', 'component_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_record_components')
    op.drop_table('service_records')
    op.drop_table('components')
    # ### end Alembic commands ###
