"""expand asset model and add vehicle_meta

Revision ID: 724fc5983761
Revises: 5fa6eb76fb6f
Create Date: 2026-04-09 09:24:56.569971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724fc5983761'
down_revision: Union[str, Sequence[str], None] = '5fa6eb76fb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_meta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('current_mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('insurance_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.add_column('assets', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('make', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('serial_number', sa.String(length=200), nullable=True))
    op.add_column('assets', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('assets', sa.Column('purchase_vendor', sa.String(length=200), nullable=True))
    op.add_column('assets', sa.Column('warranty_expiration', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('warranty_notes', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('assets', sa.Column('photo', sa.String(length=500), nullable=True))
    op.add_column('assets', sa.Column('retired_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('retired_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'retired_reason')
    op.drop_column('assets', 'retired_date')
    op.drop_column('assets', 'photo')
    op.drop_column('assets', 'location')
    op.drop_column('assets', 'warranty_notes')
    op.drop_column('assets', 'warranty_expiration')
    op.drop_column('assets', 'purchase_vendor')
    op.drop_column('assets', 'purchase_price')
    op.drop_column('assets', 'purchase_date')
    op.drop_column('assets', 'serial_number')
    op.drop_column('assets', 'year')
    op.drop_column('assets', 'model_name')
    op.drop_column('assets', 'make')
    op.drop_column('assets', 'subcategory')
    op.drop_table('vehicle_meta')
    # ### end Alembic commands ###
